--- #YAML:1.0
name:                Shape-RegularPolygon
version:             0.01
abstract:            Object that treats the shape of the regular polygon
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kazuyoshi Tomita <tomita@bit-hive.com>
